### PR TITLE
Prefer constant over variable

### PR DESCRIPTION
**Pull request by qrazi**

### CODE REVIEW

**Review by bdelespierre — CHANGES_REQUESTED** [review]
Thanks for your contibution :+1: 

However, unlike symfony/console commands, Laravel commands don't have those constants built-in.

It triggers this:
```
Error: Undefined class constant 'SUCCESS'
```

I suggest you add the `const` statement in the command as well.

**Comment by qrazi** [comment]
Ah, sorry, missed the automatic checks. And the `--prefer-lowest` is new to me... ':)

Minimal version of `symfony/console` is 5.0.0. The class constant was introduced in 5.1.0. That's why I missed it when running tests locally. I'll have a look at introducing the class constant, but it does feel a bit redundant to me in the longer run.

**Comment by qrazi** [comment]
Now all checks are completed. I rebased and squashed around a bit with the commits, but I think this looks OK?

**Review by bdelespierre — APPROVED** [review]

**Comment by bdelespierre** [comment]
Looks good :ok_hand: Thanks for your contribution :+1:

**Pull request merged**
